version: "3.7"
services:
  flask-app:
    build: .
    image: flask-frontend:latest
    expose: 
    - 5500
  nginx:
    image: nginx:latest
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
